name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "skynet13" #Must be unique in Heroku
          heroku_email: "ckpvthuongft@gmail.com"
          healthcheck: "https://skynet13.herokuapp.com/"
          rollbackonhealthcheckfailed: true